# Generated by Django 4.2.6 on 2023-10-15 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Stage Name"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+2348037286666",
                        max_length=30,
                        region=None,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bio"
                    ),
                ),
                (
                    "music_class",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Music Class"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=55, verbose_name="Company Name"
                    ),
                ),
                (
                    "sor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="State of Residence"
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        blank=True,
                        max_length=225,
                        null=True,
                        verbose_name="Local Government Area",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=225, verbose_name="Address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        default="NG",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        default="NG",
                        max_length=5,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="State"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=75, null=True, verbose_name="city"
                    ),
                ),
                ("dob", models.DateField(null=True, verbose_name="Date of Birth")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
